language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"
install:
    - "pip install ."
    - "pip install flake8 flake8-docstrings"
    - "Pip install yamllint"
    - "pip install -r requirements.txt"
script:
    - "python tests/bananabot_test.py"
    - "python -m flake8 bananabot/"
    - "yamllint config.yaml"
